package com.mib.users.models;
// Generated Oct 11, 2018 6:31:29 PM by Hibernate Tools 5.3.6.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Address generated by hbm2java
 */
@Entity
public class Address implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer slno;
	private Integer pid;
	private String address;
	private String street;
	private String city;
	private String state;
	private String country;
	private Double latitude;
	private Double longitude;

	public Address() {
	}

	public Address(Integer pid, String address, String street, String city, String state, String country,
			Double latitude, Double longitude) {
		this.pid = pid;
		this.address = address;
		this.street = street;
		this.city = city;
		this.state = state;
		this.country = country;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Integer getSlno() {
		return this.slno;
	}

	public void setSlno(Integer slno) {
		this.slno = slno;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	@Override
	public String toString() {
		return "Address [slno=" + slno + ", pid=" + pid + ", address=" + address + ", street=" + street + ", city="
				+ city + ", state=" + state + ", country=" + country + ", latitude=" + latitude + ", longitude="
				+ longitude + "]";
	}

}
